export const KNOWN_CATEGORIES = {
  restaurant: "amenity=restaurant",
  restaurants: "amenity=restaurant",
  "fast food": "amenity=fast_food",
  "fast-food": "amenity=fast_food",
  fastfood: "amenity=fast_food",
  kebab: "cuisine=kebab",
  kebabs: "cuisine=kebab",
  pizza: "cuisine=pizza",
  pizzeria: "cuisine=pizza",
  sushi: "cuisine=japanese",
  café: "amenity=cafe",
  cafe: "amenity=cafe",
  bar: "amenity=bar",
  bars: "amenity=bar",
  pub: "amenity=pub",

  cinéma: "amenity=cinema",
  cinémas: "amenity=cinema",
  théâtre: "amenity=theatre",
  théâtres: "amenity=theatre",
  musée: "tourism=museum",
  musées: "tourism=museum",
  concert: "amenity=concert_hall",
  festival: "leisure=amusement_arcade",
  karaoké: "amenity=karaoke_box",
  karaoke: "amenity=karaoke_box",
  arcade: "amenity=amusement_arcade",
  "escape game": "leisure=escape_game",
  escape: "leisure=escape_game",
  "réalité virtuelle": "leisure=virtual_reality",
  vr: "leisure=virtual_reality",

  piscine: "leisure=swimming_pool",
  piscines: "leisure=swimming_pool",
  patinoire: "leisure=ice_rink",
  skatepark: "leisure=skate_park",
  parc: "leisure=park",
  parcs: "leisure=park",
  lac: "natural=water",
  plage: "natural=beach",
  forêt: "landuse=forest",
  forêt: "landuse=wood",
  "salle de sport": "leisure=fitness_centre",
  gymnase: "leisure=sports_centre",
  stade: "leisure=stadium",
  trampoline: "leisure=trampoline_park",
  trampolines: "leisure=trampoline_park",
  escalade: "sport=climbing",
  "salle d’escalade": "sport=climbing",
  accrobranche: "leisure=adventure_park",
  accrobranche: "sport=obstacle_course",
  "parc d'attractions": "tourism=theme_park",
  bowling: "leisure=bowling_alley",

  kayak: "sport=kayaking",
  kayaking: "sport=kayaking",
  canoë: "sport=canoe",
  canoe: "sport=canoe",
  "canoë kayak": "sport=kayaking",

  mjc: "amenity=community_centre",
  "maison des jeunes": "amenity=community_centre",
  club: "amenity=nightclub",
  boîte: "amenity=nightclub",
  discothèque: "amenity=nightclub",

  supermarché: "shop=supermarket",
  supermarchés: "shop=supermarket",
  centrecommercial: "shop=mall",
  centrecommerciaux: "shop=mall",
  marché: "amenity=marketplace",
  brocante: "shop=second_hand",

  foodtruck: "amenity=fast_food",
  "food truck": "amenity=fast_food",
};
